app/comments/__init__.py
from flask import Blueprint

comments = Blueprint('comments', __name__)

from app.comments import routes

app/comments/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app, abort
from flask_login import current_user, login_required

from app import db
from app.forms import CommentForm
from app.model import Comment, User
from app.comments import comments


@comments.route('/reply/<int:id>', methods=['GET', 'POST'])
@login_required
def reply(id): # comment_id 当前评论
    comments_id_list = Comment.view_dialogue(id)
    print(comments_id_list)
    comments = [Comment.query.get_or_404(id) for id in comments_id_list]
    reply_id = request.args.get('replyid')
    post_id = request.args.get('postid')
    print(reply_id)
    reply_user = User.query.get(Comment.query.get_or_404(reply_id).author_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, type="comment",
                          reply_id=reply_id,
                          reply_name=reply_user.username,
                          post_id=post_id,
                          author_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.', category="success")
        return redirect(url_for(".reply", id=comment.id)+"?replyid=%s&postid=%s" % (reply_id, post_id))
    return render_template('comments/reply.html', title="Reply",
                           form=form,
                           reply_user=reply_user,
                           comments=comments)


@comments.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    comment = Comment.query.get_or_404(id)
    post_id = request.args.get('postid')
    print(post_id, comment.author_id, comment.post_id)
    if current_user.id != comment.post_id and current_user.id != comment.author_id:
        abort(403)
    db.session.delete(db.session.query(Comment).get(id))
    db.session.commit()
    flash("delete complete")
    return redirect(request.referrer)

app/templates/comments/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('main.user', username=comment.author.username) }}">
                {% if comment.author.avatar != None %}
                    <img class="img-rounded profile-thumbnail" src="/static/avatars/{{comment.author.avatar}}">
                {% else %}
                    <img class="img-rounded profile-thumbnail" src="{{comment.author.get_avatar(70)}}">
                {% endif %}

            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>{#TODO: 悬浮标签： #}

            <div class="comment-author">
                <a href="{{ url_for('main.user', username=comment.author.username) }}">{{ comment.author.username }}</a>
                {% if comment.type == "comment" %}
                <span class="badge badge-pill badge-primary">
                    @ <a href="{{ url_for('main.user', username=comment.reply_name) }}" style="color: #fff;">{{ comment.reply_name }}</a>
                </span>
                {%  endif %}
            </div>
            <div class="comment-body">
                {{ comment.body }}
            </div>

            <div class="post-footer">
                <a href="{{ url_for('comments.reply', id=comment.id) }}?replyid={{comment.id}}&postid={{comment.post_id}}">
                    <span class="badge badge-pill badge-primary"> Reply </span>
                </a>
{#            {{ current_user.id }}/{{ comment.post_id }}/{{ comment.image_id }}/{{ comment.author_id }}#}
                {% if current_user.id == comment.post_id or current_user.id == comment.image_id or current_user.id == comment.author_id %}
                <a href="{{ url_for('comments.delete', id=comment.id) }}?postid={{comment.post_id}}">
                    <span class="badge badge-pill badge-danger"> Delete </span>
                </a>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/comments/reply.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% import "_macros.html" as macros %}
{% block title %}Dialogue{% endblock %}

{% block app_content %}
<h2>Dialogue with {{ reply_user.username }}</h2>

{% include 'comments/_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.reply', fragment='#comments', id=comment.id) }}
</div>
{% endif %}
<div class="comment-form">
    {{ render_form(form) }}
</div>
{% endblock %}