app/gallery/__init__.py
from flask import Blueprint

gallery = Blueprint('gallery', __name__)

from app.gallery import routes

app/gallery/routes.py
import os

from flask import render_template, flash, current_app, redirect, url_for, abort, request
from flask_login import login_required, current_user

from app.gallery import gallery
from app.model import Image, Comment
from app import db, photos
from app.forms import ImageForm, CommentForm


@gallery.route('/', methods=['GET', 'POST'])
@gallery.route('/index', methods=['GET', 'POST'])
def index():
    offset = int(request.args.get('offset')) if request.args.get('offset') else 1
    image_sum = db.session.query(Image).count()
    images = db.session.query(Image)[0:4*offset]
    return render_template('gallery/index.html', title='Gallery',
                           path="/static/uploads",
                           offset=offset,
                           image_sum=image_sum,
                           images=images)


@gallery.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = ImageForm()
    if form.validate_on_submit():
        image = Image(author_id=current_user.id,
                      filename=photos.save(form.photo.data),
                      describe=form.describe.data)
        db.session.add(image)
        db.session.commit()
        flash('File uploaded.', category="success")
    return render_template('gallery/upload.html', title='Gallery', form=form)


@gallery.route('/<int:id>', methods=['GET', 'POST'])
def detail(id):
    image = Image.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, type="image",
                          image_id=image.id,
                          author_id=current_user._get_current_object().id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.', category="success")
        return redirect(url_for('.detail', id=image.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (image.comments.count() - 1) // \
               current_app.config['COMMENTS_PER_PAGE'] + 1
    pagination = image.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('gallery/detail.html', title='Photo Detail',
                           image=image,form=form,
                           path="/static/uploads",
                           comments=comments,
                           pagination=pagination)


@gallery.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    image = Image.query.get_or_404(id)
    if current_user.id != image.author_id:
        abort(403)
    file_path = photos.path(image.filename)
    os.remove(file_path)
    db.session.delete(image)
    db.session.commit()
    flash('The image has been deleted.', category="success")
    return redirect(url_for('gallery.index'))


@gallery.route('/loadmore/<int:offset>', methods=['GET', 'POST'])
def loadmore(offset):
    image_sum = db.session.query(Image).count()
    if offset*4 >= image_sum:
        flash('没有更多图片了，或许你可以上传？', category="warning")
        redirect(url_for('gallery.index', offset=offset))
    return redirect(url_for('gallery.index', offset=offset+1))

app/templates/gallery/_image.html
{% macro image_card(image,path,style="") %}

<div class="card" style="{{ style }}" onclick="window.location='{{ url_for("gallery.detail",id=image.id) }}'">
    <img class="card-img-top" src="{{ path }}/{{ image.filename }}" rel="nofollow" alt="Card image cap">
    <div class="card-body">
        <p class="card-text">{{ image.describe }}</p>
    </div>
</div>
{% endmacro %}

app/templates/gallery/detail.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% import "_macros.html" as macros %}
{% block title %}Flasky - Post{% endblock %}

{% block app_content %}
<h2>Detail</h2>
{% import 'gallery/_image.html' as show_image %}
{{ show_image.image_card(image,path) }}
<div class="comment-form">
    {{ render_form(form) }}
</div>
{% include 'comments/_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.detail', fragment='#comments', id=image.id) }}
</div>
{% endif %}

{% endblock %}

app/templates/gallery/index.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% import "_macros.html" as macros %}
{% import "gallery/_image.html" as show_image %}
{% block title %}Flasky - Gallery{% endblock %}

{% block app_content %}
    <div class="profile-page sidebar-collapse tab-content tab-space">
    <p>图库当前共有 {{ image_sum }} 张图片</p>
        <div class="tab-pane active text-center gallery" id="studio" style="width: 100%">
            <div class="row" >
                <div class="col-md-3 ml-auto" style="max-width: 50em;">
                    {% for image in images %}
                    {% if image.id % 2 == 1 %}
                        {{ show_image.image_card(image,path,style="width: 20rem;") }}
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="col-md-3 mr-auto" style="max-width: 50em;">
                    {% for image in images %}
                    {% if image.id % 2 == 0 %}
                        {{ show_image.image_card(image,path,style="width: 20rem;") }}
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
     <a class="btn btn-primary" href="{{ url_for("gallery.loadmore",offset=offset) }}">没看够？</a>
     <a class="btn btn-success" href="{{ url_for("gallery.upload") }}">我要上传</a>
    {# TODO: 下拉自动加载 #}
{% endblock %}

app/templates/gallery/upload.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h3>Upload photo</h3>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}