app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates/errors')

from app.main import routes, yxh
from app.model import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

"""
main:
- /, /index
    - PostForm
- /explore
- /edit_profile
"""

app/main/routes.py
from datetime import datetime

from flask import render_template, flash, redirect, url_for, request, current_app, abort
from flask_login import current_user, login_required, logout_user

from app import db, avatars
from app.forms import EditProfileForm, EmptyForm, PostForm
from app.main import main
from app.model import User, Post, Role


@main.before_app_request
def before_request():
    Role.insert_roles()
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    # g.locale = str(get_locale())


# TODO: 简化重复代码
@main.route('/', methods=['GET', 'POST'])
@main.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        body = Post(body=form.body.data, author=current_user)
        db.session.add(body)
        db.session.commit()
        flash('Your post is now live!', category="success")
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    for post in posts:
        post.body_html = Post.breviary(post.body_html)
    show_followed = False
    return render_template('index.html', title='Home', form=form,
                           show_followed=show_followed,
                           posts=posts, pagination=pagination)


@main.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    for post in posts:
        post.body_html = Post.breviary(post.body_html)
    return render_template('index.html', title='Explore',
                           posts=posts, pagination=pagination)


@main.route('/user/<username>')
@login_required
def user(username):
    c_user = User.query.filter_by(username=username).first_or_404()
    fans = c_user.followers.all()
    page = request.args.get('page', 1, type=int)
    pagination = c_user.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    for post in posts:
        post.body_html = Post.breviary(post.body_html)
    form = EmptyForm()
    return render_template('main/user.html',
                           user=c_user, posts=posts,
                           pagination=pagination,
                           form=form, fans=fans)


@main.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        # head portrait
        current_user.avatar = avatars.save(form.avatar.data)
        db.session.commit()
        flash('Your changes have been saved.', category="info")
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', title='Edit Profile', form=form)


@main.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        f_user = User.query.filter_by(username=username).first()
        if f_user is None:
            flash('User %s not found.' % username, category="danger")
            return redirect(url_for('main.index'))
        if f_user == current_user:
            flash('You cannot follow yourself!', category="warning")
            return redirect(url_for('main.user', username=username))
        current_user.follow(f_user)
        db.session.commit()
        flash('You are following %s!' % username, category="success")
        return redirect(url_for('main.user', username=username))
    else:
        return redirect(url_for('main.index'))


@main.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        c_user = User.query.filter_by(username=username).first()
        if c_user is None:
            flash('User %s not found.' % username, category="danger")
            return redirect(url_for('main.index'))
        if c_user == current_user:
            flash('You cannot unfollow yourself!', category="warning")
            return redirect(url_for('main.user', username=username))
        current_user.unfollow(c_user)
        db.session.commit()
        flash('You are not following %s.' % username, category="success")
        return redirect(url_for('main.user', username=username))
    else:
        return redirect(url_for('main.index'))


@main.route('/del_user')
@login_required
def del_user(id):
    if current_user.id != id:
        abort(403)
    db.session.delete(db.session.query(User).get(id))
    # TODO: delete fans relationship
    db.session.commit()
    logout_user()


@main.route('/remake')
def remake():
    return render_template('main/remake.html')

app/templates/main/edit_profile.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h3>Edit Profile</h3>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
            <a class="badge badge-pill badge-danger" href="{{ url_for("main.del_user") }}">注销用户</a>
        </div>
    </div>
{% endblock %}

app/templates/main/remake.html
{% extends "base.html" %}

{% block app_content %}
        <p align="center">
        <iframe src="https://liferestart.syaro.io/view/index.html"
            width="300"
            height="600">
        </iframe>
        </p>
{% endblock %}

app/templates/main/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}


{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td width="256px">
                {% if user.avatar %}
                <img src="/static/avatars/{{user.avatar}}" width="256px">
                {% endif %}
            </td>
            <td>
                <h2>User: {{ user.username }}</h2>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>{% endif %}
                <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
                {% elif not current_user.is_following(user) %}
                <p>
                    <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Follow', class_='btn btn-default') }}
                    </form>
                </p>
                {% else %}
                <p>
                    <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Unfollow', class_='btn btn-default') }}
                    </form>
                </p>
                {% endif %}
            </td>
        </tr>
    </table>
    <h3>Posts by {{ user.username }}</h3>
    {% include 'posts/_posts.html' %}
    {% if pagination %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, '.user', username=user.username) }}
    </div>
    {% endif %}
    <hr>
    <h3>Fans of {{ user.username }}</h3>
    <table>
        {% for fan in fans %}
            <tr>
                <td>
                {% if fan.avatar %}
                    <img src="/static/avatars/{{fan.avatar}}" width="70px">
                {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('main.user', username=fan.username) }}"> {{ fan.username }} </a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

app/templates/main/yxh.html
{% extends "base.html" %}

{% block app_content %}
    <div class="container">
    <h1>营销号生成器</h1>
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <form action="{{url_for('main.result')}}" method="POST" >
                <div class="form-group">
                    <lable>主体：</lable>
                    <input type="text" name="name" class="form-control" placeholder="全国高校" required />
                </div>
                <div class="form-group">
                    <lable>事件：</lable>
                    <input type="text" name="event" class="form-control" placeholder="不开学了" required />
                </div>
                <input type="submit" value="生成" class="btn btn-primary"/>
            </form>
        </div>
        <div class="col-sm-6 col-xs-12">
            <p class="lead" style="word-break:break-all; word-wrap:break-all;">{{txt}}</p>
        </div>
    </div>
    </div>
{% endblock %}