app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__, template_folder='templates/errors')

from app.posts import routes

app/posts/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, current_app, abort
from flask_login import current_user, login_required

from app import db
from app.forms import CommentForm, PostForm
from app.model import Post, Comment
from app.posts import posts


@posts.route('/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.', category="success")
        return redirect(url_for('.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) // \
            current_app.config['COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('posts/post.html', title="Post", posts=[post], form=form,
                           comments=comments, pagination=pagination)


@posts.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        flash('The post has been updated.', category="success")
        return redirect(url_for('.post', id=post.id))
    form.body.data = post.body
    return render_template('posts/edit_post.html', form=form, id=post.id)


@posts.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:
        abort(403)
    db.session.delete(post)
    # TODO: delete associative comments
    db.session.commit()
    flash('The post has been deleted.', category="success")
    return redirect(url_for('main.index'))

app/templates/posts/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                {% if post.author.avatar != None %}
                    <img class="img-rounded profile-thumbnail" src="/static/avatars/{{post.author.avatar}}">
                {% else %}
                    <img class="img-rounded profile-thumbnail" src="{{post.author.get_avatar(70)}}">
                {% endif %}
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('main.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
            <div class="post-footer">
                <a href="{{ url_for('posts.post', id=post.id) }}#comments">
                    <span class="badge badge-pill badge-primary">{{ post.comments.count() }} Comments</span>
                </a>
                {% if current_user == post.author %}
                <a href="{{ url_for('posts.edit', id=post.id) }}">
                    <span class="badge badge-pill badge-info">Edit</span>
                </a>
                <a href="{{ url_for('posts.delete', id=post.id) }}">
                    <span class="badge badge-pill badge-danger"> Delete </span>
                </a>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/posts/edit_post.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}


{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

{% block title %}Flasky - Edit Post{% endblock %}

{% block app_content %}
<h2>
    <h1>Edit Post</h1>
</h2>
<div>
    {{ render_form(form) }}
    <br>
    <a type="button" class="btn btn-danger" href="{{url_for('posts.delete', id=id)}}">Delete</a>
</div>
{% endblock %}

app/templates/posts/post.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}
{% import "_macros.html" as macros %}
{% block title %}Flasky - Post{% endblock %}

{% block app_content %}
{% include 'posts/_posts.html' %}
<div class="comment-form">
    {{ render_form(form) }}
</div>
{% include 'comments/_comments.html' %}
{% if pagination %}
<div class="paginationpa">
    {{ macros.pagination_widget(pagination, '.post', fragment='#comments', id=posts[0].id) }}
</div>
{% endif %}
{% endblock %}